version: "3.8"
services:
  whatsapp-node-api:
    build:
      context: .
    command: yarn start
    restart: always
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
